// Generated by IcedCoffeeScript 108.0.13
(function() {
  var e, mp, pp, set_opt, set_opts, _opts;

  try {
    mp = require('msgpack');
  } catch (_error) {
    e = _error;
  }

  if (mp == null) {
    try {
      pp = require('@msgpack/msgpack');
      mp = pp;
    } catch (_error) {
      e = _error;
    }
  }

  if ((mp == null) && (pp == null)) {
    throw new Error("Need either msgpack or purepack to run");
  }

  _opts = {};

  exports.set_opt = set_opt = function(k, v) {
    return _opts[k] = v;
  };

  exports.set_opts = set_opts = function(o) {
    return _opts = o;
  };

  exports.use_byte_arrays = function() {
    var err;
    if (pp == null) {
      try {
        return mp = pp = require('@msgpack/msgpack');
      } catch (_error) {
        err = _error;
        throw new Error("Cannot use_byte_arrays without purepack!");
      }
    }
  };

  exports.pack = function(b) {
    var encoded;
    encoded = mp.encode(b);
    return Buffer.from(encoded.buffer, encoded.byteOffset, encoded.byteLength);
  };

  exports.unpack = function(b) {
    var dat, err;
    err = dat = null;
    try {
      dat = mp.decode(b);
    } catch (_error) {
      err = _error;
    }
    return [err, dat];
  };

}).call(this);
