<<<<<<< eaaec2517bd09b548252a253a4f604bca900d32c
exports.version = "1.1.13";
=======
// Generated by IcedCoffeeScript 108.0.11
(function() {
  exports.version = "1.1.11";

}).call(this);
>>>>>>> support sending cancelled
